UPDATE weekly_blogs
SET content = 'Every meaningful relationship begins somewhere. Sometimes it begins with a conversation, a shared experience, or even a simple act of kindness. Yet God never intended our relationships to remain at the surface. Throughout this four-week journey, we will move beyond learning how love is expressed to discovering how God uses every relationship to transform us into the likeness of Christ. Each week builds upon the previous one, inviting us to grow from communication to character, from daily choices to lifelong commitment.'
WHERE id = 1;

UPDATE weekly_blogs
SET content = 'Love cannot flourish when it is consistently misunderstood. During the first week, we begin by exploring Gary Chapman''s five love languages and how they help us recognize the unique ways people both express and receive love. While these love languages provide valuable insight into healthy communication, they are only the beginning of a much greater journey. God uses these channels not merely to improve our relationships, but to open our hearts to deeper transformation.\n\n**This week''s reflection will explore:**\n\n1. **The Five Love Languages** — Understanding Words of Affirmation, Acts of Service, Receiving Gifts, Quality Time, and Physical Touch as practical expressions of love.\n2. **Learning to Love Intentionally** — Discovering how recognizing another person''s love language strengthens communication, trust, and emotional connection.\n3. **The Doorway to Something Greater** — Seeing the love languages not as the destination, but as the first step toward Christ-centered relationships that transform both ourselves and others.'
WHERE id = 2;

UPDATE weekly_blogs
SET content = 'Once we understand how love is communicated, we must ask a deeper question: *What does genuine biblical love actually look like?* This week shifts our attention from methods of communication to the character that gives love its lasting power. Through Paul''s timeless words in 1 Corinthians 13, we discover that authentic love is revealed not by emotion alone, but by patience, humility, kindness, forgiveness, and steadfast faithfulness.\n\n**This week''s reflection will explore:**\n\n1. **Love According to Scripture** — Examining Paul''s description of love and why it remains God''s standard for every relationship.\n2. **Character Before Communication** — Understanding that speaking another person''s love language is most effective when it flows from a transformed heart.\n3. **Growing into Christlikeness** — Allowing the Holy Spirit to develop the qualities of love that endure through every season of life.'
WHERE id = 3;

UPDATE weekly_blogs
SET content = 'Healthy relationships are not built on occasional grand gestures but on faithful daily decisions. Every conversation, every response, every act of forgiveness, and every sacrifice becomes an opportunity to choose love over self-interest. This week reminds us that discipleship is formed through countless ordinary choices that gradually shape both our character and our relationships.\n\n**This week''s reflection will explore:**\n\n1. **Choosing Grace Every Day** — Learning to replace criticism with encouragement, impatience with compassion, and resentment with forgiveness.\n2. **Habits That Build Healthy Relationships** — Developing practical disciplines that cultivate trust, humility, and genuine care for others.\n3. **Transformation Through Obedience** — Discovering how everyday decisions become the pathway through which God forms us into the image of Christ.'
WHERE id = 4;

UPDATE weekly_blogs
SET content = 'The journey concludes by looking beyond feelings and circumstances to the enduring nature of covenant love. Biblical commitment is more than staying together during good times; it is a reflection of Christ''s unwavering faithfulness toward His people. As we embrace covenant love, we discover that lasting relationships are sustained not merely by emotion, but by faithful devotion rooted in God''s unchanging promises.\n\n**This week''s reflection will explore:**\n\n1. **The Meaning of Covenant Love** — Understanding the difference between temporary commitment and lifelong faithfulness.\n2. **Remaining Faithful Through Every Season** — Learning how perseverance, forgiveness, and sacrificial love strengthen relationships during both joy and hardship.\n3. **Reflecting the Faithfulness of Christ** — Embracing a life of commitment that points others to the steadfast love God has shown us through Jesus Christ.'
WHERE id = 5;
